name: Pack .NET Template

on:
  push:
    branches:
      - main

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Pack .NET Template Project
      run: dotnet pack --configuration Release --no-build --output nupkg

    - name: Publish to NuGet.org
      run: dotnet nuget push "nupkg/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json